version: 2

updates:
  # Maintain dependencies for npm/yarn
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    versioning-strategy: lockfile-only
    labels:
      - javascript
      - dependencies
      - auto-squash

  # Maintain dependencies for Composer
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
    versioning-strategy: lockfile-only
    labels:
      - php
      - dependencies
      - auto-squash

  # Maintain dependencies for Github Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - actions
      - dependencies
      - auto-squash
