name: Build assets

on:
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [created]

env:
  node-version: 18

jobs:
  #############
  # Build
  #############
  build:
    runs-on: ubuntu-latest
    name: Build Assets

    strategy:
      fail-fast: false

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      # Yarn
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: yarn
      - name: Install yarn dependencies
        run: yarn install --frozen-lockfile
      - name: Build assets
        run: yarn run build
