name: Build assets

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [created]

env:
  node-version: 20

jobs:
  #############
  # Build
  #############
  build:
    runs-on: ubuntu-latest
    name: Build Assets

    strategy:
      fail-fast: false

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      # Yarn
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.node-version }}
          cache: yarn

      - name: Install yarn dependencies
        run: yarn install --immutable

      - name: Get version
        id: version
        run: |
          echo "release=$(git describe --abbrev=0 --tags --exact-match $GITHUB_SHA 2>/dev/null || git log --pretty="%h" -n1 $GITHUB_SHA)" >> $GITHUB_OUTPUT

      - name: Set environment variables
        # if: github.event_name == 'push' && env.SENTRY_AUTH_TOKEN != ''
        run: |
          { \
            echo "VITE_PROD_SOURCE_MAPS=true"; \
            echo "SENTRY_ORG=$SENTRY_ORG"; \
            echo "SENTRY_PROJECT=$SENTRY_PROJECT"; \
            echo "SENTRY_RELEASE=${{ steps.version.outputs.release }}"; \
          } > .env
        env:
          SENTRY_ORG: ${{ vars.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ vars.SENTRY_PROJECT }}
          SENTRY_RELEASE: ${{ steps.version.outputs.release }}

      - name: Build assets
        run: yarn run build
        env:
          SENTRY_AUTH_TOKEN: ${{ github.event_name == 'push' && secrets.SENTRY_AUTH_TOKEN || '' }}
          SENTRY_RELEASE: ${{ steps.version.outputs.release }}
