name: Docker

on:
  push:
    branches:
      - main

  schedule:
    - cron: '0 0 1 * *' #At 00:00 on day-of-month 1.

concurrency:
  group: Docker ${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker-run:
    runs-on: ubuntu-latest
    name: Docker build developpment

    strategy:
      fail-fast: false

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v4
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.CR_USER }}
          password: ${{ secrets.CR_PAT }}

    # Build docker
      - name: Docker build
        id: docker_build
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:main
          labels: ${{ steps.docker_meta.outputs.labels }}
          file: Dockerfile
          context: .

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}


  deploy:
    runs-on: ubuntu-latest
    name: Deploy on staging
    needs: docker-run

    environment: staging

    steps:
      - name: Post request
        run: curl -sSL -u ":$TOKEN" -X POST -H "Content-type: application/json" "$URL" -d "$PAYLOAD"
        env:
          URL: ${{ secrets.URL }}
          PAYLOAD: ${{ secrets.PAYLOAD }}
          TOKEN: ${{ secrets.TOKEN }}
