name: Build and test

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  release:
    types: [created]

concurrency:
  group: Build ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  id-token: write

jobs:
  tests:
    name: Run tests
    uses: monicahq/workflows/.github/workflows/laravel.yml@v2
    with:
      php-versions: "['8.2']"
      connections: "['sqlite','mysql']"
      default-php-version: '8.2'
      default-connection: sqlite
      database_name: webauthn
      project: asbiin_laravel-webauthn-example
      organization: asbiin-github
      mock-assets: false
      node-version: '20'
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
